version: '3'
services:
  nettewebs:
    container_name: nettewebs
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./webs/:/var/www/webs
      - ./log/:/var/log/
    ports:
      - '127.0.0.1:80:80'
      # - '80:80'
      # First line allows access only from this computer, second one from all computers in your network.
      # Only one line can be uncommented at a time!
